from __future__ import annotations

from workers.search.engine import (
    FAST_TIMEOUT,
    MAX_SOURCES,
    OVERFETCH_FACTOR,
    PER_PAGE_CHAR_CAP,
    SCRAPE_TIMEOUT,
    SEARXNG_TIMEOUT,
    SUMMARY_BATCH_SIZE,
    SUMMARY_INPUT_CHAR_CAP,
    SUMMARY_MAX_TOKENS,
    _dedupe,
    searxng_search,
)
from workers.search.extraction import (
    _ACCEPTABLE_CONTENT_TYPES,
    _EXTRACTION_GOAL_BY_INTENT,
    _SOFT_CONTENT_TYPES,
    _background_graph_write,
    _extract_one_page,
    _extraction_goal_for,
    extract_from_pages,
)
from workers.search.heuristics import (
    _CODE_PREFIXES,
    _EXPLICIT_SEARCH_PATTERNS,
    _EXTERNAL_QUESTION,
    _NO_SEARCH_TRIGGER_WORDS,
    _definitely_no_search,
    _explicit_search_intent,
    needs_web_search,
)
from workers.search.intent import (
    ALL_INTENTS,
    CHAT_INTENT_CHITCHAT,
    CHAT_INTENT_COMPARISON,
    CHAT_INTENT_CONTEXTUAL,
    CHAT_INTENT_EXPLANATORY,
    CHAT_INTENT_FACTUAL,
    CHAT_INTENT_RECOMMENDATION,
    CHAT_INTENT_RESEARCH,
    CHAT_INTENT_TROUBLESHOOTING,
    CHAT_INTENTS,
    CODE_INTENT_BUILD,
    CODE_INTENT_DEBUG,
    CODE_INTENT_EXPLAIN,
    CODE_INTENT_LOOKUP,
    CODE_INTENT_OPTIMISE,
    CODE_INTENT_REFACTOR,
    CODE_INTENT_REVIEW,
    CODE_INTENT_SECURITY,
    CODE_INTENT_TEST,
    CODE_INTENTS,
    INTENT_RESPONSE_TEMPLATE,
    INTENT_ROUTE_CHAT,
    INTENT_ROUTE_CODE,
    INTENT_ROUTE_TASK,
    INTENT_ROUTES,
    INTENT_SEARCH_POLICY,
    SEARCH_POLICY_CONTEXTUAL,
    SEARCH_POLICY_FOCUSED,
    SEARCH_POLICY_FULL,
    SEARCH_POLICY_NONE,
    TASK_INTENT_REMEMBER,
    TASK_INTENT_SCHEDULE,
    TASK_INTENT_SEARCH_EXPLICIT,
    TASK_INTENT_SUMMARISE,
    TASK_INTENTS,
    _derive_policy,
    _fallback_intent,
    _format_history_for_classifier,
    _INTENT_CLASSIFIER_PROMPT,
    classify_message_intent,
)
from workers.search.models import (
    _ENRICHMENT_SAFE_ROLES,
    _fast_model,
    _resolve_safe_model,
    _tool_model,
)
from workers.search.orchestrator import (
    _POLICY_BUDGETS,
    _run_search_inner,
    _suggest_sources_from_search,
    run_web_search,
)
from workers.search.queries import (
    _current_year,
    _quote_entity,
    build_failure_context,
    generate_search_queries,
    reformulate_query,
    rerank_candidates,
)
from workers.search.scraping import (
    MAX_RESPONSE_BYTES,
    PLAYWRIGHT_FETCH_TIMEOUT,
    _STEALTH_SCRIPT,
    _nocodb_truthy,
    _scrape_with_httpx,
    playwright_fetch,
    scrape_page,
)
from workers.search.temporal import (
    build_prompt_date_header,
    build_temporal_context,
    now_in_chat_tz,
)
from workers.search.urls import (
    BROWSER_HEADERS,
    BROWSER_UA,
    SCRAPE_BLOCKLIST,
    _INJECTION_PATTERNS,
    _is_blocklisted,
    _is_safe_url,
    _sanitise_url,
    _strip_injection_patterns,
)
